export const textTheme = {
  text_small: {fontSize: 12},
  text_smallBold: {fontSize: 12, fontWeight: 'bold'},
  text_smallUnderscore: {fontSize: 12, textDecorationLine: 'underline'},
  text_smallStrike: {fontSize: 12, textDecorationLine: 'line-through'},
  text_normal: {fontSize: 14},
  text_normalBold: {fontSize: 14, fontWeight: 'bold'},
  text_normalUnderscore: {fontSize: 14, textDecorationLine: 'underline'},
  text_normalStrike: {fontSize: 14, textDecorationLine: 'line-through'},
  text_subtitle: {fontSize: 16},
  text_subtitleBold: {fontSize: 16, fontWeight: 'bold'},
  text_title: {fontSize: 18},
  text_titleBold: {fontSize: 18, fontWeight: 'bold'},
  text_subheader: {fontSize: 20},
  text_subheaderBold: {fontSize: 20, fontWeight: 'bold'},
  text_header: {fontSize: 22},
  text_headerBold: {fontSize: 22, fontWeight: 'bold'},

  text_center: {width: '100%', textAlign: 'center', fontWeight: 'bold'},
};
